In [5]:
import cv2
import numpy as np
import time
img = cv2.imread('dog.jpg')

# 修改对比度与亮度
aa = cv2.convertScaleAbs(img, alpha = 1.5, beta = 30)
cv2.imwrite('output1.jpg', aa)

# 图片用数组表示
a = np.array(img)

# 修改图片像素点
l = len(a)
w = len(a[0])
print(a)

st = time.time()

a = np.clip(a.astype(np.int16) + 70, 0, 255).astype(np.uint8)

# for i in range(l):
#     for j in range(w):
#         for k in range(3):
            # a[i][j][k] = (a[i][j][k] + 70) % 256
ed = time.time()
print("********************")
print(ed - st)
print(a)
cv2.imwrite('output2.png', a)


# 显示图片
# cv2.imshow("dog", img)


[[[ 2  5  9]
  [ 2  5  9]
  [ 1  4  8]
  ...
  [17 38 90]
  [17 34 90]
  [14 31 87]]

 [[ 5  8 12]
  [ 4  7 11]
  [ 3  6 10]
  ...
  [17 38 90]
  [17 38 90]
  [16 37 89]]

 [[ 2  5  9]
  [ 2  5  9]
  [ 1  4  8]
  ...
  [16 39 89]
  [15 38 88]
  [13 36 86]]

 ...

 [[ 0  2 10]
  [ 0  2 10]
  [ 0  2 10]
  ...
  [ 3 15 39]
  [ 2 16 39]
  [ 4 18 41]]

 [[ 0  1 11]
  [ 0  1 11]
  [ 0  1 11]
  ...
  [ 2 16 39]
  [ 1 14 40]
  [ 2 15 41]]

 [[ 0  0 10]
  [ 0  0 10]
  [ 0  0 10]
  ...
  [ 6 20 43]
  [ 4 17 43]
  [ 4 17 43]]]
********************
0.04227757453918457
[[[ 72  75  79]
  [ 72  75  79]
  [ 71  74  78]
  ...
  [ 87 108 160]
  [ 87 104 160]
  [ 84 101 157]]

 [[ 75  78  82]
  [ 74  77  81]
  [ 73  76  80]
  ...
  [ 87 108 160]
  [ 87 108 160]
  [ 86 107 159]]

 [[ 72  75  79]
  [ 72  75  79]
  [ 71  74  78]
  ...
  [ 86 109 159]
  [ 85 108 158]
  [ 83 106 156]]

 ...

 [[ 70  72  80]
  [ 70  72  80]
  [ 70  72  80]
  ...
  [ 73  85 109]
  [ 72  86 109]
  [ 74  88 111]]

 [[ 70  71  81]

True

In [ ]:
print("!")