In [37]:
import numpy as np
from PIL import Image
image_path = "cat.jpg"
im = Image.open(image_path)
im.show()
im = np.array(im)
print(im)

[[[ 22  10  12]
  [ 19   7   9]
  [ 21   9  11]
  ...
  [ 90  78  56]
  [ 89  78  56]
  [ 92  81  59]]

 [[ 24  12  14]
  [ 23  11  13]
  [ 23  11  13]
  ...
  [100  87  68]
  [ 80  69  49]
  [ 96  85  65]]

 [[ 19   9  10]
  [ 22  12  13]
  [ 23  13  12]
  ...
  [ 85  72  55]
  [ 91  78  62]
  [ 90  77  61]]

 ...

 [[152 126  93]
  [145 121  87]
  [148 124  90]
  ...
  [108  77  59]
  [108  75  60]
  [ 88  52  38]]

 [[168 144 108]
  [161 139 102]
  [160 137 103]
  ...
  [128  97  76]
  [127  94  77]
  [ 99  66  49]]

 [[157 135  98]
  [156 134  97]
  [148 128  93]
  ...
  [115  87  63]
  [141 108  89]
  [136 103  86]]]


In [28]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
a.max()
a.min()
print(a.sum())
b = np.zeros((4, 2), dtype = np.int16)
c = np.array([4, 5, 6, 7, 8])
print(a + c)
print(a / c)
print(a @ c)
print(np.sqrt(a))
print(np.dot(a, c))

15
[ 5  7  9 11 13]
[0.25       0.4        0.5        0.57142857 0.625     ]
100
[1.         1.41421356 1.73205081 2.         2.23606798]
100


In [61]:
import numpy as py
import pandas as pd
s = pd.Series([1, 2, 3, 4], index = ['A', 'B', 'C', 'D'])
st = pd.Series({"a":1, "b":2, "c":3 , "d":4})
s1 = pd.Series(s, index = ["A", "C"])
print(s)
print(st)
print(s1)

A    1
B    2
C    3
D    4
dtype: int64
a    1
b    2
c    3
d    4
dtype: int64
A    1
C    3
dtype: int64


In [93]:
s = pd.Series([1, 2, 3, 4], index = ["A", "B", "C", "D"])
s.name = "test"
print(s)
print(s.index)
print(s.values)
print(s.shape, s.ndim, s.size)
print(s.dtype, s.name)

# 显示索引
print(s.loc['A':'D']) 

# 隐式索引
print(s.iloc[0:2])  

# 这个不允许切片
print(s.at['A']) 


A    1
B    2
C    3
D    4
Name: test, dtype: int64
Index(['A', 'B', 'C', 'D'], dtype='str')
[1 2 3 4]
(4,) 1 4
int64 test
A    1
B    2
C    3
D    4
Name: test, dtype: int64
A    1
B    2
Name: test, dtype: int64
1


In [82]:
s = pd.Series([1, 2, 3, 4], index = ["A", "B", "C", "D"])
print(s["A"])
print(s[s < 3])
# 默认五行数据
print(s.head(2))
print(s.tail(1))


1
A    1
B    2
dtype: int64
A    1
B    2
dtype: int64
D    4
dtype: int64


In [94]:
import pandas as pd
import numpy as np
s = pd.Series([1, 2, np.nan, np.nan], index = ['A', 'B', 'C', 'D'], name = 'nonono')
# 描述信息
print(s.describe())

# 约等于 index：属性 keys（）：方法
print(s.keys())

# 寻找缺失值
print(s.isna())

# 查看是否存在
print(s.isin([1, 3]))

print(s.std())

print(s.var())


count    2.000000
mean     1.500000
std      0.707107
min      1.000000
25%      1.250000
50%      1.500000
75%      1.750000
max      2.000000
Name: nonono, dtype: float64
Index(['A', 'B', 'C', 'D'], dtype='str')
A    False
B    False
C     True
D     True
Name: nonono, dtype: bool
A     True
B    False
C    False
D    False
Name: nonono, dtype: bool
0.7071067811865476
0.5
